-- dbgui PostgreSQL test fixture — exercises every object type the schema tree
-- should render. Version-safe for PG 12..18.

DROP SCHEMA IF EXISTS txui_demo CASCADE;
CREATE SCHEMA txui_demo;
COMMENT ON SCHEMA txui_demo IS 'dbgui demo schema';

DROP SCHEMA IF EXISTS txui_other CASCADE;
CREATE SCHEMA txui_other;

SET search_path = txui_demo, public;

-- ── Types ────────────────────────────────────────────────────────────
CREATE TYPE order_status AS ENUM ('new', 'paid', 'shipped', 'cancelled');
CREATE TYPE addr AS (street text, city text, zip text);
CREATE DOMAIN email AS text CHECK (VALUE ~ '^[^@]+@[^@]+$');

-- ── Sequences ────────────────────────────────────────────────────────
CREATE SEQUENCE invoice_seq START 1000;

-- ── Tables ───────────────────────────────────────────────────────────
CREATE TABLE customers (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    contact     email,
    billing     addr,
    created_at  timestamptz NOT NULL DEFAULT now(),
    tags        text[]      DEFAULT '{}',
    meta        jsonb       DEFAULT '{}'::jsonb,
    balance     numeric(14,2) NOT NULL DEFAULT 0
);
COMMENT ON TABLE  customers      IS 'Demo customers';
COMMENT ON COLUMN customers.name IS 'Display name';

CREATE TABLE orders (
    id           bigserial PRIMARY KEY,
    customer_id  bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    status       order_status NOT NULL DEFAULT 'new',
    total_cents  bigint NOT NULL CHECK (total_cents >= 0),
    total_eur    numeric GENERATED ALWAYS AS (total_cents / 100.0) STORED,
    placed_at    timestamptz NOT NULL DEFAULT now(),
    note         text
);

-- composite / multi-column PK, no surrogate key
CREATE TABLE order_items (
    order_id  bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    line_no   int    NOT NULL,
    sku       text   NOT NULL,
    qty       int    NOT NULL DEFAULT 1,
    PRIMARY KEY (order_id, line_no)
);

-- a table with NO primary key at all (data-browser edge case)
CREATE TABLE audit_raw (
    at      timestamptz DEFAULT now(),
    payload jsonb
);

-- COMPOSITE foreign key. The referencing columns are declared in the OPPOSITE
-- order to the referenced ones, so a query that pairs them by anything other
-- than ordinal position produces a visibly wrong mapping rather than an
-- accidentally-correct one.
CREATE TABLE item_notes (
    line_no  int    NOT NULL,
    order_id bigint NOT NULL,
    note     text,
    PRIMARY KEY (order_id, line_no),
    CONSTRAINT item_notes_item_fk
        FOREIGN KEY (order_id, line_no)
        REFERENCES order_items (order_id, line_no) ON DELETE CASCADE
);

-- ── Partitioned table ────────────────────────────────────────────────
CREATE TABLE events (
    id       bigint GENERATED BY DEFAULT AS IDENTITY,
    at       timestamptz NOT NULL,
    kind     text,
    PRIMARY KEY (id, at)
) PARTITION BY RANGE (at);
CREATE TABLE events_2026q1 PARTITION OF events
    FOR VALUES FROM ('2026-01-01') TO ('2026-04-01');
CREATE TABLE events_2026q2 PARTITION OF events
    FOR VALUES FROM ('2026-04-01') TO ('2026-07-01');
CREATE TABLE events_default PARTITION OF events DEFAULT;

-- ── Indexes: btree, unique, partial, expression, gin ─────────────────
CREATE INDEX        idx_orders_customer   ON orders (customer_id);
CREATE UNIQUE INDEX idx_customers_contact ON customers (contact);
CREATE INDEX        idx_orders_open       ON orders (placed_at) WHERE status <> 'cancelled';
CREATE INDEX        idx_customers_lower   ON customers (lower(name));
CREATE INDEX        idx_customers_meta    ON customers USING gin (meta);
CREATE INDEX        idx_orders_desc       ON orders (placed_at DESC NULLS LAST);

-- ── Views + materialized view ────────────────────────────────────────
CREATE VIEW v_open_orders AS
    SELECT o.id, c.name, o.total_cents, o.status
    FROM orders o JOIN customers c ON c.id = o.customer_id
    WHERE o.status IN ('new', 'paid');

CREATE MATERIALIZED VIEW mv_customer_totals AS
    SELECT c.id, c.name, count(o.id) AS orders, coalesce(sum(o.total_cents),0) AS cents
    FROM customers c LEFT JOIN orders o ON o.customer_id = c.id
    GROUP BY c.id, c.name;
CREATE UNIQUE INDEX ON mv_customer_totals (id);

-- ── Functions, procedure, aggregate, trigger ─────────────────────────
CREATE FUNCTION customer_order_count(cid bigint) RETURNS bigint
    LANGUAGE sql STABLE AS $$ SELECT count(*) FROM orders WHERE customer_id = cid $$;

CREATE FUNCTION order_total_eur(o orders) RETURNS numeric
    LANGUAGE sql IMMUTABLE AS $$ SELECT o.total_cents / 100.0 $$;

CREATE PROCEDURE reset_demo() LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM order_items;
    DELETE FROM orders;
END $$;

-- user-defined aggregate: prokind 'a', which pg_get_functiondef() refuses
CREATE FUNCTION sum_cents_sfunc(bigint, bigint) RETURNS bigint
    LANGUAGE sql IMMUTABLE AS $$ SELECT $1 + coalesce($2, 0) $$;
CREATE AGGREGATE total_cents(bigint) (
    SFUNC = sum_cents_sfunc, STYPE = bigint, INITCOND = '0'
);

CREATE FUNCTION touch_order() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.placed_at := coalesce(NEW.placed_at, now());
    RETURN NEW;
END $$;

CREATE TRIGGER trg_touch_order BEFORE INSERT ON orders
    FOR EACH ROW EXECUTE FUNCTION touch_order();

CREATE TRIGGER trg_orders_audit AFTER UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION touch_order();

-- ── Row-level security ───────────────────────────────────────────────
ALTER TABLE audit_raw ENABLE ROW LEVEL SECURITY;
CREATE POLICY audit_all ON audit_raw USING (true);

-- ── Second schema, to prove schema switching works ───────────────────
CREATE TABLE txui_other.lookup (
    code text PRIMARY KEY,
    label text NOT NULL
);
CREATE VIEW txui_other.v_lookup AS SELECT * FROM txui_other.lookup;

-- ── Data ─────────────────────────────────────────────────────────────
INSERT INTO customers (name, contact, billing, tags, meta, balance)
SELECT 'Customer ' || g,
       'c' || g || '@example.com',
       ROW('Main St ' || g, 'Prague', '1000' || (g % 10))::addr,
       ARRAY['tag' || (g % 3), 'vip'],
       jsonb_build_object('tier', g % 4, 'active', g % 2 = 0),
       (g * 13.37)::numeric(14,2)
FROM generate_series(1, 500) g;

INSERT INTO orders (customer_id, status, total_cents, note)
SELECT (random() * 499 + 1)::bigint,
       (ARRAY['new','paid','shipped','cancelled']::order_status[])[(random()*3+1)::int],
       (random() * 500000)::bigint,
       CASE WHEN g % 7 = 0 THEN NULL ELSE 'note ' || g END
FROM generate_series(1, 2000) g;

INSERT INTO order_items (order_id, line_no, sku, qty)
SELECT o.id, l, 'SKU-' || (o.id % 50), (random()*5+1)::int
FROM orders o CROSS JOIN generate_series(1, 3) l;

INSERT INTO events (at, kind)
SELECT '2026-01-01'::timestamptz + (g || ' hours')::interval, 'kind' || (g % 5)
FROM generate_series(1, 3000) g;

INSERT INTO audit_raw (payload)
SELECT jsonb_build_object('n', g) FROM generate_series(1, 100) g;

INSERT INTO item_notes (order_id, line_no, note)
SELECT oi.order_id, oi.line_no, 'note for line ' || oi.line_no
FROM order_items oi WHERE oi.order_id % 20 = 0;

INSERT INTO txui_other.lookup VALUES ('A','Alpha'), ('B','Bravo'), ('C','Charlie');

REFRESH MATERIALIZED VIEW mv_customer_totals;
ANALYZE;
